name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DWSPP_BUILD_TESTS=ON
          -DWSPP_BUILD_EXAMPLES=OFF
          -DWSPP_BUILD_PLAYGROUND=OFF
          -DWSPP_INSTALL=OFF

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build --output-on-failure